#!/usr/bin/awk -f
BEGIN {
	inCode=0
	sawEndCode=0
}
(/^>/ && (inCode==0 || NR==1)) {
	if (sawEndCode==0) {
		print "\\begin{code}"
	}
	sub("^> ", "", $0)
	print
	inCode=1
	next
}
/^>/ {
	sub("^>$","> ",$0)
	sub("^> ","",$0)
	print
	next
}
/^$/ && (inCode==1) {
	sawEndCode=1
	inCode=0
	print
	next
}
{
	if (sawEndCode==1) {
		print "\\end{code}"
		sawEndCode=0
	}
	print
}
END {
	if (inCode==1) {
		print "\\end{code}"
	}
}
