#!/bin/sh

SMARTYPANTS=cat
type smartypants >/dev/null 2>&1 && \
    SMARTYPANTS="$(which smartypants) -a Bb"

if [ $# -ne 1 ] && [ $# -ne 2 ]; then
	echo 'Usage: markdown-lhs file [style-sheet]'
	exit 1
fi

printf '\xef\xbb\xbf<html>\n<head><title>%s</title>\n' $1
printf '<link rel="stylesheet" href="%s" type="text/css" />' ${2:-default.css}
echo '</head><body>'
sed -e 's@^> @    @' -e 's@\f@* * *@g' $1 | markdown | ${SMARTYPANTS}
echo '</body></html>'
